# Packages I generally use
library(tidyverse)
library(lme4)
library(lmerTest)
library(cowplot)
library(plyr)
library(dplyr)
library(readr)
library(tidyr)
library(purrr)
library(effectsize)
library(DataExplorer)
library(GGally)
library(ggfortify)
library(ghibli)
library(shiny)
library(ggpubr)
library(rstatix)
library(plotly) 
library(umap) 
library(tsne)
library(viridis)


# Extras:
library(RColorBrewer)
library(see)
library(performance)
library(patchwork)
library(outliers)
library(readxl)
library(tibble)
library(flextable)
library(kableExtra)
library(gt)
library(gtsummary)
library(lsr)
library(apaTables)
library(knitr)
library(viridis)
library(forcats)
library(hrbrthemes)
library(vegan)
library(ggvegan)
library(iml)
library(tidyposterior)
library(skimr)
library(tidyverse)
library(tidymodels)
library(nnet)
library(kknn)
library(sjPlot)
library(sjmisc) 
library(effects)
library(sjstats)
library(webshot)

# Some of John Curtin's functions
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/fun_modeling.R?raw=true")
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/fun_ml.R?raw=true")
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/fun_eda.R?raw=true")
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/fun_plots.R?raw=true")



library(conflicted)
tidymodels_prefer()

conflicts_prefer(dplyr::mutate)
conflicts_prefer(dplyr::arrange)
conflicts_prefer(dplyr::summarize)
conflicts_prefer(yardstick::accuracy)
conflicts_prefer(rstanarm::logit)
conflicts_prefer(readr::cols)
conflicts_prefer(base::`:`)
conflicts_prefer(broom::bootstrap)
conflicts_prefer(svglite::font_face)